name: 🚀 Deploy

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  prettier:
    name: 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 20

      - name: 📥 Install deps
        run: bun install

      - name: 💅 Prettier
        run: npm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 20

      - name: 📥 Install deps
        run: bun install

      - name: 🔎 Type check
        run: bun run types:check
